# fly.toml app configuration file generated for hirewise-ai on 2025-05-29T22:24:43Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hirewise-ai'
primary_region = 'lax'

[build]
  dockerfile = "apps/api/Dockerfile"
  context = "../.."

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
