from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Tenant',
    'User',
    'Profile',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Tenant': {
        'users': 'User',
    },
    'User': {
        'tenant': 'Tenant',
        'profiles': 'Profile',
    },
    'Profile': {
        'User': 'User',
    },
}

# fmt: on