[project]
name = "database"
version = "0.1.0"
description = ""
authors = [
    {name = "Mac",email = "mac@macanderson.com"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "prisma (>=0.15.0,<0.16.0)"
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pylint",
    "mypy",
    "flake8"
]

[tool.poetry]
packages = [{include = "database", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.prisma]
schema = "prisma/schema.prisma"

[tool.ruff]
exclude = ["src/database/**"]

[tool.pylint]
ignore-paths = ["src/database"]

[tool.mypy]
exclude = ["src/database/"]

[tool.flake8]
exclude = ["src/database"]
