# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template enums.py.jinja --
from ._compat import StrEnum


class CandidateStatus(StrEnum):
    NEW = 'NEW'
    REVIEWING = 'REVIEWING'
    INTERVIEWING = 'INTERVIEWING'
    OFFERED = 'OFFERED'
    HIRED = 'HIRED'
    REJECTED = 'REJECTED'

class InterviewStatus(StrEnum):
    SCHEDULED = 'SCHEDULED'
    COMPLETED = 'COMPLETED'
    CANCELLED = 'CANCELLED'
    RESCHEDULED = 'RESCHEDULED'

class InterviewType(StrEnum):
    PHONE = 'PHONE'
    VIDEO = 'VIDEO'
    IN_PERSON = 'IN_PERSON'
    TECHNICAL = 'TECHNICAL'

class JobStatus(StrEnum):
    OPEN = 'OPEN'
    CLOSED = 'CLOSED'
    DRAFT = 'DRAFT'
    ARCHIVED = 'ARCHIVED'

class JobType(StrEnum):
    FULL_TIME = 'FULL_TIME'
    PART_TIME = 'PART_TIME'
    CONTRACT = 'CONTRACT'
    INTERNSHIP = 'INTERNSHIP'
    FREELANCE = 'FREELANCE'

class Role(StrEnum):
    USER = 'USER'
    ADMIN = 'ADMIN'
    RECRUITER = 'RECRUITER'
    HIRING_MANAGER = 'HIRING_MANAGER'

