from __future__ import annotations
# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# fmt: off
# -- template metadata.py.jinja --


PRISMA_MODELS: set[str] = {
    'Assessment',
    'Candidate',
    'Interview',
    'Job',
    'Profile',
    'Token',
    'User',
}

RELATIONAL_FIELD_MAPPINGS: dict[str, dict[str, str]] = {
    'Assessment': {
        'Candidate': 'Candidate',
    },
    'Candidate': {
        'Assessment': 'Assessment',
        'Job': 'Job',
        'User': 'User',
        'Interview': 'Interview',
    },
    'Interview': {
        'Candidate': 'Candidate',
    },
    'Job': {
        'Candidate': 'Candidate',
        'User': 'User',
    },
    'Profile': {
        'User': 'User',
    },
    'Token': {
        'User': 'User',
    },
    'User': {
        'Candidate': 'Candidate',
        'Job': 'Job',
        'Profile': 'Profile',
        'Token': 'Token',
    },
}

# fmt: on