name: Deploy FastAPI Server to Fly.io

on:
  push:
    branches: [ main ]
    paths: [ 'apps/api/**' ]

jobs:
  deploy-backend-to-fly:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - run: |
        cd apps/api
        flyctl deploy --remote-only
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
